sudo: required
services:
  - docker

before_install:
  - docker build -t kromsik/docker-react -f Dockerfile.dev .

script:
  - docker run kromsik/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-108467340653"
  bucket_path: "docker" # exactly the same as app name
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
